require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe QuestionsController, :type => :controller do
  render_views

  before(:each) do
    @organization = FactoryGirl.create(:organization)
  end

  describe "GET index" do
    before(:each) do
      sign_in @organization.user
    end
  
    it "assigns all questions as @questions" do
      question = FactoryGirl.create(:question, :organization => @organization)
      get :index
      expect(assigns(:questions)).to eq([question])
    end
  end

  describe "POST create" do
    before(:each) do
      sign_in @organization.user
    end

    describe "with valid params" do
      it "creates a new Question" do
        expect {
          post :create, {:question => {:question => "Q1?", :input_type => "text"}}
        }.to change(Question, :count).by(1)
      end

      it "assigns a newly created question as @question" do
        post :create, {:question => {:question => "Q1?", :input_type => "text"}}
        expect(assigns(:question)).to be_a(Question)
        expect(assigns(:question)).to be_persisted
      end

      it "redirects to the questions index page" do
        post :create, {:question => {:question => "Q1?", :input_type => "text"}}
        expect(response).to redirect_to(questions_path)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved question as @question" do
        # Trigger the behavior that occurs when invalid params are submitted
        Question.any_instance.stub(:save).and_return(false)
        post :create, {:question => {:question => "Q1?", :input_type => "text"}}
        assigns(:question).should be_a_new(Question)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Question.any_instance.stub(:save).and_return(false)
        post :create, {:question => {:question => "Q1?", :input_type => "text"}}
        expect(response).to render_template("new")
      end
    end
  end

  describe "DELETE destroy" do
    describe 'if the user is signed in as an organization,' do
      before(:each) do
        sign_in @organization.user
        @question = FactoryGirl.create(:question, :organization => @organization)
      end
    
      it "destroys the requested question" do
        expect {
          delete :destroy, :id => @question.id
        }.to change(Question, :count).by(-1)
      end

      it "redirects to the questions index" do
        delete :destroy, :id => @question.id
        expect(response).to redirect_to(questions_path)
      end
      
      it "redirects to the dashboard if the requested question does not exist" do
        delete :destroy, :id => 500
        expect(response).to redirect_to(dashboard_path)
      end
      
      it "redirects to the dashboard if the requested question does not belong to this organization" do
        question = FactoryGirl.create(:question, :organization => FactoryGirl.create(:organization))
        delete :destroy, :id => question.id
        expect(response).to redirect_to(dashboard_path)
      end
    end
    
    describe 'if the user is signed in as a client,' do
      before(:each) do
        sign_in FactoryGirl.create(:client).user
      end
      
      it "redirects to the dashboard" do
        delete :destroy, :id => 1
        expect(response).to redirect_to(dashboard_path)
      end
      
      it "displays the notice 'You do not have the right permissions to view this page.'" do
        delete :destroy, :id => 1
        expect(flash[:notice]).to eq('You do not have the right permissions to view this page.')
      end
    end
    
    describe 'if the user is not signed in,' do
      it "redirects to the login page" do
        delete :destroy, :id => 1
        expect(response).to redirect_to(new_user_session_path)
      end
      
      it "displays the notice 'Please log in.'" do
        delete :destroy, :id => 1
        expect(flash[:notice]).to eq('Please log in.')
      end
    end
  end

  describe "GET edit" do
    before(:each) do
      sign_in @organization.user
      @question = FactoryGirl.create(:question, :organization => @organization)
    end

    it "assigns the requested question as @question" do
      get :edit, :id => @question.id
      assigns(:question).should eq(@question)
    end
  end

  describe "POST update" do
    before(:each) do
      sign_in @organization.user
      @question = FactoryGirl.create(:question, :organization => @organization)
    end

    describe "with valid params" do
      it "displays the updated question instead of the old question" do
        post :update, {:id => @question.id, :question => {:question => "updated q?", :input_type => "text"}}
        get :index
        expect(response.body).to include("updated q?")
        expect(response.body).not_to include(@question.question)
      end

      it "redirects to the questions index page" do
        post :update, {:id => @question.id, :question => {:question => "updated q?", :input_type => "text"}}
        expect(response).to redirect_to(questions_path)
      end

      it "displays the notice 'Question was successfully updated.'" do
        post :update, {:id => @question.id, :question => {:question => "updated q?", :input_type => "text"}}
        expect(flash[:notice]).to eq('Question was successfully updated.')
      end
    end

    describe "with invalid params" do
      it "re-renders the 'edit' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Question.any_instance.stub(:update_attributes).and_return(false)
        post :update, {:id => @question.id, :question => {:question => "updated q?", :input_type => "text"}}
        expect(response).to render_template("edit")
      end
    end
  end

end
